/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author jnosp
 */
public class VistaRegistroHuesped extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroHuesped
     */
    public VistaRegistroHuesped() {
        initComponents();
    }

    public JButton getBotonguardarhuesped() {
        return botonguardarhuesped;
    }

    public JButton getBotonlimpiarhuesped() {
        return botonlimpiarhuesped;
    }

    public JButton getBotonvolver_resgistrohuesped() {
        return botonvolver_resgistrohuesped;
    }

    public JTextField getTxtdireccionhuesped_registrohuesped() {
        return txtdireccionhuesped_registrohuesped;
    }

    public JTextField getTxtfechantohuesped_registrohuesped() {
        return txtfechantohuesped_registrohuesped;
    }

    public JTextField getTxtidhuesped_registrohuesped() {
        return txtidhuesped_registrohuesped;
    }

    public JTextField getTxtnombrehuesped_resgistrohuesped() {
        return txtnombrehuesped_resgistrohuesped;
    }

    public JTextField getTxttelefonohuesped_registrohuesped() {
        return txttelefonohuesped_registrohuesped;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblhuesped = new javax.swing.JLabel();
        lblnombrehuesped = new javax.swing.JLabel();
        lbldireccionhuesped = new javax.swing.JLabel();
        lbltelefonohuesped = new javax.swing.JLabel();
        lblfechanto = new javax.swing.JLabel();
        botonguardarhuesped = new javax.swing.JButton();
        botonlimpiarhuesped = new javax.swing.JButton();
        botonvolver_resgistrohuesped = new javax.swing.JButton();
        txtidhuesped_registrohuesped = new javax.swing.JTextField();
        txtdireccionhuesped_registrohuesped = new javax.swing.JTextField();
        txtnombrehuesped_resgistrohuesped = new javax.swing.JTextField();
        txttelefonohuesped_registrohuesped = new javax.swing.JTextField();
        txtfechantohuesped_registrohuesped = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhuesped.setText("ID Huésped");
        getContentPane().add(lblhuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 57, 91, -1));

        lblnombrehuesped.setText("Nombre completo");
        getContentPane().add(lblnombrehuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 99, 116, -1));

        lbldireccionhuesped.setText("Dirección");
        getContentPane().add(lbldireccionhuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 144, 76, -1));

        lbltelefonohuesped.setText("Teléfono");
        getContentPane().add(lbltelefonohuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 189, 76, -1));

        lblfechanto.setText("Fecha de nacimiento");
        getContentPane().add(lblfechanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 235, 135, -1));

        botonguardarhuesped.setBackground(new java.awt.Color(0, 0, 0));
        botonguardarhuesped.setForeground(new java.awt.Color(255, 255, 255));
        botonguardarhuesped.setText("Guardar");
        getContentPane().add(botonguardarhuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 269, -1, -1));

        botonlimpiarhuesped.setBackground(new java.awt.Color(0, 0, 0));
        botonlimpiarhuesped.setForeground(new java.awt.Color(255, 255, 255));
        botonlimpiarhuesped.setText("Limpiar");
        getContentPane().add(botonlimpiarhuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 269, -1, -1));

        botonvolver_resgistrohuesped.setBackground(new java.awt.Color(0, 0, 0));
        botonvolver_resgistrohuesped.setForeground(new java.awt.Color(255, 255, 255));
        botonvolver_resgistrohuesped.setText("Volver");
        getContentPane().add(botonvolver_resgistrohuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 269, -1, -1));
        getContentPane().add(txtidhuesped_registrohuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 54, 136, -1));
        getContentPane().add(txtdireccionhuesped_registrohuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 141, 136, -1));
        getContentPane().add(txtnombrehuesped_resgistrohuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 96, 136, -1));
        getContentPane().add(txttelefonohuesped_registrohuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 186, 136, -1));
        getContentPane().add(txtfechantohuesped_registrohuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 229, 136, -1));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroHuesped().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonguardarhuesped;
    private javax.swing.JButton botonlimpiarhuesped;
    private javax.swing.JButton botonvolver_resgistrohuesped;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbldireccionhuesped;
    private javax.swing.JLabel lblfechanto;
    private javax.swing.JLabel lblhuesped;
    private javax.swing.JLabel lblnombrehuesped;
    private javax.swing.JLabel lbltelefonohuesped;
    private javax.swing.JTextField txtdireccionhuesped_registrohuesped;
    private javax.swing.JTextField txtfechantohuesped_registrohuesped;
    private javax.swing.JTextField txtidhuesped_registrohuesped;
    private javax.swing.JTextField txtnombrehuesped_resgistrohuesped;
    private javax.swing.JTextField txttelefonohuesped_registrohuesped;
    // End of variables declaration//GEN-END:variables
}
