/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author jnosp
 */
public class VistaRegistroHotel extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroHotel
     */
    public VistaRegistroHotel() {
        initComponents();
    }

    public JButton getBotonguardarhotel() {
        return botonguardarhotel;
    }

    public JButton getBotonlimpiarhotel() {
        return botonlimpiarhotel;
    }

    public JButton getBotonvolver_registrohotel() {
        return botonvolver_registrohotel;
    }

    public JComboBox<String> getComboboxcategoria() {
        return comboboxcategoria;
    }

    public JTextField getTxtanioinauguracion() {
        return txtanioinauguracion;
    }

    public JTextField getTxtdireccionhotel() {
        return txtdireccionhotel;
    }

    public JTextField getTxtnombrehotel() {
        return txtnombrehotel;
    }

    public JTextField getTxttelefonohotel() {
        return txttelefonohotel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnombrehotel = new javax.swing.JLabel();
        txtnombrehotel = new javax.swing.JTextField();
        lbldireccionhotel = new javax.swing.JLabel();
        lbltelefonohotel = new javax.swing.JLabel();
        lblanioinauguracion = new javax.swing.JLabel();
        lblcategoria = new javax.swing.JLabel();
        botonguardarhotel = new javax.swing.JButton();
        botonlimpiarhotel = new javax.swing.JButton();
        botonvolver_registrohotel = new javax.swing.JButton();
        txtdireccionhotel = new javax.swing.JTextField();
        txttelefonohotel = new javax.swing.JTextField();
        txtanioinauguracion = new javax.swing.JTextField();
        comboboxcategoria = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblnombrehotel.setText("Nombre del hotel");
        getContentPane().add(lblnombrehotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 115, -1));
        getContentPane().add(txtnombrehotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 12, 175, -1));

        lbldireccionhotel.setText("Dirección");
        getContentPane().add(lbldireccionhotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 63, 92, -1));

        lbltelefonohotel.setText("Teléfono");
        getContentPane().add(lbltelefonohotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 92, -1));

        lblanioinauguracion.setText("Año de inauguración");
        getContentPane().add(lblanioinauguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 152, 115, -1));

        lblcategoria.setText("Categoría");
        getContentPane().add(lblcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 192, 92, -1));

        botonguardarhotel.setBackground(new java.awt.Color(0, 0, 0));
        botonguardarhotel.setForeground(new java.awt.Color(255, 255, 255));
        botonguardarhotel.setText("Guardar");
        getContentPane().add(botonguardarhotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 237, -1, -1));

        botonlimpiarhotel.setBackground(new java.awt.Color(0, 0, 0));
        botonlimpiarhotel.setForeground(new java.awt.Color(255, 255, 255));
        botonlimpiarhotel.setText("Limpiar");
        getContentPane().add(botonlimpiarhotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 237, -1, -1));

        botonvolver_registrohotel.setBackground(new java.awt.Color(0, 0, 0));
        botonvolver_registrohotel.setForeground(new java.awt.Color(255, 255, 255));
        botonvolver_registrohotel.setText("Volver");
        getContentPane().add(botonvolver_registrohotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 237, -1, -1));
        getContentPane().add(txtdireccionhotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 60, 175, -1));
        getContentPane().add(txttelefonohotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 107, 175, -1));
        getContentPane().add(txtanioinauguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 149, 175, -1));

        comboboxcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Estrella", "2 Estrellas", "3 Estrellas", "4 Estrellas", "5 Estrellas" }));
        getContentPane().add(comboboxcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 189, 114, -1));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonguardarhotel;
    private javax.swing.JButton botonlimpiarhotel;
    private javax.swing.JButton botonvolver_registrohotel;
    private javax.swing.JComboBox<String> comboboxcategoria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblanioinauguracion;
    private javax.swing.JLabel lblcategoria;
    private javax.swing.JLabel lbldireccionhotel;
    private javax.swing.JLabel lblnombrehotel;
    private javax.swing.JLabel lbltelefonohotel;
    private javax.swing.JTextField txtanioinauguracion;
    private javax.swing.JTextField txtdireccionhotel;
    private javax.swing.JTextField txtnombrehotel;
    private javax.swing.JTextField txttelefonohotel;
    // End of variables declaration//GEN-END:variables
}
