/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author jnosp
 */
public class VistaRegistrar extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistrar
     */
    public VistaRegistrar() {
        initComponents();
    }

    public JButton getBotonregistraragencia() {
        return botonregistraragencia;
    }

    public JButton getBotonregistrarhabitacion() {
        return botonregistrarhabitacion;
    }

    public JButton getBotonregistrarhotel() {
        return botonregistrarhotel;
    }

    public JButton getBotonregistrarhuesped() {
        return botonregistrarhuesped;
    }

    public JButton getBotonregistrarreservacion() {
        return botonregistrarreservacion;
    }

    public JButton getBotonregresomenu_resgistro() {
        return botonregresomenu_resgistro;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonregistrarhotel = new javax.swing.JButton();
        botonregistrarreservacion = new javax.swing.JButton();
        botonregistrarhabitacion = new javax.swing.JButton();
        botonregistrarhuesped = new javax.swing.JButton();
        botonregistraragencia = new javax.swing.JButton();
        botonregresomenu_resgistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonregistrarhotel.setText("Registrar Hotel");

        botonregistrarreservacion.setText("Registrar Resevación");

        botonregistrarhabitacion.setText("Registrar Habitación");

        botonregistrarhuesped.setText("Registrar Huésped");

        botonregistraragencia.setText("Registrar Agencia de Viajes");

        botonregresomenu_resgistro.setText("Volver al Menú Principal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(botonregistrarhotel)
                .addGap(29, 29, 29)
                .addComponent(botonregistrarhabitacion)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(botonregresomenu_resgistro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addComponent(botonregistrarreservacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonregistrarhuesped)
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonregistraragencia)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonregistrarhotel)
                    .addComponent(botonregistrarhabitacion))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonregistrarreservacion)
                    .addComponent(botonregistrarhuesped))
                .addGap(34, 34, 34)
                .addComponent(botonregistraragencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(botonregresomenu_resgistro)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonregistraragencia;
    private javax.swing.JButton botonregistrarhabitacion;
    private javax.swing.JButton botonregistrarhotel;
    private javax.swing.JButton botonregistrarhuesped;
    private javax.swing.JButton botonregistrarreservacion;
    private javax.swing.JButton botonregresomenu_resgistro;
    // End of variables declaration//GEN-END:variables
}
