/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author jnosp
 */
public class VistaRegistroHabitacion extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroHabitacion
     */
    public VistaRegistroHabitacion() {
        initComponents();
    }

    public JButton getBotonguardarhabitacion() {
        return botonguardarhabitacion;
    }

    public JButton getBotonlimpiarhabitacion() {
        return botonlimpiarhabitacion;
    }

    public JButton getBotonvolver_registrohabitacion() {
        return botonvolver_registrohabitacion;
    }

    public JComboBox<String> getComboboxidhotel() {
        return comboboxidhotel;
    }

    public JTextField getTxtidhabitacion() {
        return txtidhabitacion;
    }

    public JTextField getTxtnumerohabitacion() {
        return txtnumerohabitacion;
    }

    public JTextField getTxttipohabitacion() {
        return txttipohabitacion;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblidhabitacion = new javax.swing.JLabel();
        lbltipohabitacion = new javax.swing.JLabel();
        lblnumerohabitacion = new javax.swing.JLabel();
        lblidhotel = new javax.swing.JLabel();
        botonguardarhabitacion = new javax.swing.JButton();
        botonlimpiarhabitacion = new javax.swing.JButton();
        botonvolver_registrohabitacion = new javax.swing.JButton();
        txtnumerohabitacion = new javax.swing.JTextField();
        txtidhabitacion = new javax.swing.JTextField();
        txttipohabitacion = new javax.swing.JTextField();
        comboboxidhotel = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblidhabitacion.setText("ID habitación");
        getContentPane().add(lblidhabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 60, 106, -1));

        lbltipohabitacion.setText("Tipo");
        getContentPane().add(lbltipohabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 88, 62, -1));

        lblnumerohabitacion.setText("Número de habitación");
        getContentPane().add(lblnumerohabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 119, 134, -1));

        lblidhotel.setText("ID hotel");
        getContentPane().add(lblidhotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 159, 59, -1));

        botonguardarhabitacion.setBackground(new java.awt.Color(0, 0, 0));
        botonguardarhabitacion.setForeground(new java.awt.Color(255, 255, 255));
        botonguardarhabitacion.setText("Guardar");
        getContentPane().add(botonguardarhabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 215, -1, -1));

        botonlimpiarhabitacion.setBackground(new java.awt.Color(0, 0, 0));
        botonlimpiarhabitacion.setForeground(new java.awt.Color(255, 255, 255));
        botonlimpiarhabitacion.setText("Limpiar");
        getContentPane().add(botonlimpiarhabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 215, -1, -1));

        botonvolver_registrohabitacion.setBackground(new java.awt.Color(0, 0, 0));
        botonvolver_registrohabitacion.setForeground(new java.awt.Color(255, 255, 255));
        botonvolver_registrohabitacion.setText("Volver");
        getContentPane().add(botonvolver_registrohabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 215, -1, -1));
        getContentPane().add(txtnumerohabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 119, 130, -1));
        getContentPane().add(txtidhabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 57, 130, -1));
        getContentPane().add(txttipohabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 85, 130, -1));

        getContentPane().add(comboboxidhotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 159, 130, -1));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroHabitacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonguardarhabitacion;
    private javax.swing.JButton botonlimpiarhabitacion;
    private javax.swing.JButton botonvolver_registrohabitacion;
    private javax.swing.JComboBox<String> comboboxidhotel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblidhabitacion;
    private javax.swing.JLabel lblidhotel;
    private javax.swing.JLabel lblnumerohabitacion;
    private javax.swing.JLabel lbltipohabitacion;
    private javax.swing.JTextField txtidhabitacion;
    private javax.swing.JTextField txtnumerohabitacion;
    private javax.swing.JTextField txttipohabitacion;
    // End of variables declaration//GEN-END:variables
}
