/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author jnosp
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    public JButton getBontonconsultar() {
        return bontonconsultar;
    }

    public JButton getBontonregitrar() {
        return bontonregitrar;
    }

    public JButton getBotonsalida() {
        return botonsalida;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bontonconsultar = new javax.swing.JButton();
        bontonregitrar = new javax.swing.JButton();
        botonsalida = new javax.swing.JButton();
        lbltitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bontonconsultar.setBackground(new java.awt.Color(0, 0, 0));
        bontonconsultar.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        bontonconsultar.setForeground(new java.awt.Color(255, 255, 255));
        bontonconsultar.setText("Consultar");
        bontonconsultar.setBorderPainted(false);
        bontonconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bontonconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(bontonconsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 103, 131, 54));

        bontonregitrar.setBackground(new java.awt.Color(0, 0, 0));
        bontonregitrar.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        bontonregitrar.setForeground(new java.awt.Color(255, 255, 255));
        bontonregitrar.setText("Registrar");
        bontonregitrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bontonregitrarActionPerformed(evt);
            }
        });
        getContentPane().add(bontonregitrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 103, 131, 54));

        botonsalida.setBackground(new java.awt.Color(0, 0, 0));
        botonsalida.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        botonsalida.setForeground(new java.awt.Color(255, 255, 255));
        botonsalida.setText("Salir");
        getContentPane().add(botonsalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 254, 124, 42));

        lbltitulo.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        lbltitulo.setText("Sistema de Gestión Hotelera - Tranquidescanso");
        getContentPane().add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 16, 500, -1));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bontonconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bontonconsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bontonconsultarActionPerformed

    private void bontonregitrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bontonregitrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bontonregitrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bontonconsultar;
    private javax.swing.JButton bontonregitrar;
    private javax.swing.JButton botonsalida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbltitulo;
    // End of variables declaration//GEN-END:variables
}
