/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author jnosp
 */
public class VistaRegistrar extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistrar
     */
    public VistaRegistrar() {
        initComponents();
    }

    public JButton getBotonregistraragencia() {
        return botonregistraragencia;
    }

    public JButton getBotonregistrarhabitacion() {
        return botonregistrarhabitacion;
    }

    public JButton getBotonregistrarhotel() {
        return botonregistrarhotel;
    }

    public JButton getBotonregistrarhuesped() {
        return botonregistrarhuesped;
    }

    public JButton getBotonregistrarreservacion() {
        return botonregistrarreservacion;
    }

    public JButton getBotonregresomenu_resgistro() {
        return botonregresomenu_resgistro;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonregistrarreservacion = new javax.swing.JButton();
        botonregresomenu_resgistro = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botonregistrarhotel = new javax.swing.JButton();
        botonregistrarhabitacion = new javax.swing.JButton();
        botonregistrarhuesped = new javax.swing.JButton();
        botonregistraragencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonregistrarreservacion.setBackground(new java.awt.Color(0, 0, 0));
        botonregistrarreservacion.setForeground(new java.awt.Color(255, 255, 255));
        botonregistrarreservacion.setText("Registrar Resevación");
        getContentPane().add(botonregistrarreservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 133, -1, -1));

        botonregresomenu_resgistro.setBackground(new java.awt.Color(0, 0, 0));
        botonregresomenu_resgistro.setForeground(new java.awt.Color(255, 255, 255));
        botonregresomenu_resgistro.setText("Volver al Menú Principal");
        getContentPane().add(botonregresomenu_resgistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 271, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        botonregistrarhotel.setBackground(new java.awt.Color(0, 0, 0));
        botonregistrarhotel.setForeground(new java.awt.Color(255, 255, 255));
        botonregistrarhotel.setText("Registrar Hotel");

        botonregistrarhabitacion.setBackground(new java.awt.Color(0, 0, 0));
        botonregistrarhabitacion.setForeground(new java.awt.Color(255, 255, 255));
        botonregistrarhabitacion.setText("Registrar Habitación");

        botonregistrarhuesped.setBackground(new java.awt.Color(0, 0, 0));
        botonregistrarhuesped.setForeground(new java.awt.Color(255, 255, 255));
        botonregistrarhuesped.setText("Registrar Huésped");

        botonregistraragencia.setBackground(new java.awt.Color(0, 0, 0));
        botonregistraragencia.setForeground(new java.awt.Color(255, 255, 255));
        botonregistraragencia.setText("Registrar Agencia de Viajes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(botonregistrarhotel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonregistrarhuesped)
                    .addComponent(botonregistrarhabitacion))
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(botonregistraragencia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonregistrarhotel)
                    .addComponent(botonregistrarhabitacion))
                .addGap(48, 48, 48)
                .addComponent(botonregistrarhuesped)
                .addGap(39, 39, 39)
                .addComponent(botonregistraragencia)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonregistraragencia;
    private javax.swing.JButton botonregistrarhabitacion;
    private javax.swing.JButton botonregistrarhotel;
    private javax.swing.JButton botonregistrarhuesped;
    private javax.swing.JButton botonregistrarreservacion;
    private javax.swing.JButton botonregresomenu_resgistro;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
