
package Vista;

import javax.swing.JButton;

/**
 *
 * @author jnosp
 */
public class VistaConsulta extends javax.swing.JFrame {

    
    public JButton getBotonconsultaagencias() {
        return botonconsultaagencias;
    }

    public JButton getBotonconsultahabitaciones() {
        return botonconsultahabitaciones;
    }

    public JButton getBotonconsultahoteles() {
        return botonconsultahoteles;
    }

    public JButton getBotonconsultahuespedes() {
        return botonconsultahuespedes;
    }

    public JButton getBotonconsultareservas() {
        return botonconsultareservas;
    }

    /**
     * Creates new form VistaConsulta
     */
    public JButton getBotonregresomenu() {    
        return botonregresomenu_consulta;
    }

    public VistaConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonconsultahoteles = new javax.swing.JButton();
        botonconsultareservas = new javax.swing.JButton();
        botonconsultaagencias = new javax.swing.JButton();
        botonregresomenu_consulta = new javax.swing.JButton();
        botonconsultahabitaciones = new javax.swing.JButton();
        botonconsultahuespedes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonconsultahoteles.setText("Consultar Hoteles");

        botonconsultareservas.setText("Consultar Reservas");

        botonconsultaagencias.setText("Consultar Agencias");

        botonregresomenu_consulta.setText("Volver al Menú Principal");

        botonconsultahabitaciones.setText("Consultar Habitaciones");

        botonconsultahuespedes.setText("Consultar Huéspedes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonconsultareservas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonconsultahuespedes)
                        .addGap(101, 101, 101))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonconsultahoteles)
                                .addGap(18, 18, 18)
                                .addComponent(botonconsultahabitaciones))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(botonconsultaagencias)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(botonregresomenu_consulta)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonconsultahoteles)
                    .addComponent(botonconsultahabitaciones))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonconsultareservas)
                    .addComponent(botonconsultahuespedes))
                .addGap(42, 42, 42)
                .addComponent(botonconsultaagencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(botonregresomenu_consulta)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonconsultaagencias;
    private javax.swing.JButton botonconsultahabitaciones;
    private javax.swing.JButton botonconsultahoteles;
    private javax.swing.JButton botonconsultahuespedes;
    private javax.swing.JButton botonconsultareservas;
    private javax.swing.JButton botonregresomenu_consulta;
    // End of variables declaration//GEN-END:variables
}
