/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author jnosp
 */
public class VistaRegistroReserva extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroReserva
     */
    public VistaRegistroReserva() {
        initComponents();
    }

    public JButton getBotonguardarreserva() {
        return botonguardarreserva;
    }

    public JButton getBotonlimpiarreserva() {
        return botonlimpiarreserva;
    }

    public JButton getBotonvolver_resgistroreserva() {
        return botonvolver_resgistroreserva;
    }

    public JComboBox<String> getComboboxtipohabitacion_registroreserva() {
        return comboboxtipohabitacion_registroreserva;
    }

    public JTextField getTxtagencia_registroreserva() {
        return txtagencia_registroreserva;
    }

    public JTextField getTxtcantidadhabitaciones() {
        return txtcantidadhabitaciones;
    }

    public JTextField getTxtcatidadpersona() {
        return txtcatidadpersona;
    }

    public JTextField getTxtdireccion_registroreserva() {
        return txtdireccion_registroreserva;
    }

    public JTextField getTxtfechafin_registroreserva() {
        return txtfechafin_registroreserva;
    }

    public JTextField getTxtfechainicio_registroreserva() {
        return txtfechainicio_registroreserva;
    }

    public JTextField getTxtidreserva() {
        return txtidreserva;
    }

    public JTextField getTxtnombrehuesped_resgistroreserva() {
        return txtnombrehuesped_resgistroreserva;
    }

    public JTextField getTxtserviciosadicionales() {
        return txtserviciosadicionales;
    }

    public JTextField getTxttelefono_registroreserva() {
        return txttelefono_registroreserva;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblidreserva = new javax.swing.JLabel();
        lblnombrehuesped = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        botonguardarreserva = new javax.swing.JButton();
        botonlimpiarreserva = new javax.swing.JButton();
        botonvolver_resgistroreserva = new javax.swing.JButton();
        txtidreserva = new javax.swing.JTextField();
        txtnombrehuesped_resgistroreserva = new javax.swing.JTextField();
        txtfechafin_registroreserva = new javax.swing.JTextField();
        txtdireccion_registroreserva = new javax.swing.JTextField();
        txttelefono_registroreserva = new javax.swing.JTextField();
        txtagencia_registroreserva = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfechainicio_registroreserva = new javax.swing.JTextField();
        txtcatidadpersona = new javax.swing.JTextField();
        txtcantidadhabitaciones = new javax.swing.JTextField();
        comboboxtipohabitacion_registroreserva = new javax.swing.JComboBox<>();
        txtserviciosadicionales = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblidreserva.setText("ID Reserva");
        getContentPane().add(lblidreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 57, 86, -1));

        lblnombrehuesped.setText("Nombre del huésped");
        getContentPane().add(lblnombrehuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 100, 140, -1));

        jLabel3.setText("Dirección");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 140, 140, -1));

        jLabel4.setText("Teléfono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 180, 140, -1));

        jLabel5.setText("Agencia");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 220, 140, -1));

        jLabel6.setText("Fecha Fin");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 260, 85, -1));

        jLabel7.setText("Cantidad de Personas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 300, 140, -1));

        jLabel8.setText("Tipo y cantidad de habitaciones");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 340, 189, -1));

        jLabel9.setText("Servicios adicionales");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 380, 141, -1));

        botonguardarreserva.setBackground(new java.awt.Color(0, 0, 0));
        botonguardarreserva.setForeground(new java.awt.Color(255, 255, 255));
        botonguardarreserva.setText("Guardar");
        getContentPane().add(botonguardarreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 417, -1, -1));

        botonlimpiarreserva.setBackground(new java.awt.Color(0, 0, 0));
        botonlimpiarreserva.setForeground(new java.awt.Color(255, 255, 255));
        botonlimpiarreserva.setText("Limpiar");
        getContentPane().add(botonlimpiarreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 417, -1, -1));

        botonvolver_resgistroreserva.setBackground(new java.awt.Color(0, 0, 0));
        botonvolver_resgistroreserva.setForeground(new java.awt.Color(255, 255, 255));
        botonvolver_resgistroreserva.setText("Volver");
        getContentPane().add(botonvolver_resgistroreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 417, -1, -1));
        getContentPane().add(txtidreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 57, 122, -1));
        getContentPane().add(txtnombrehuesped_resgistroreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 97, 122, -1));
        getContentPane().add(txtfechafin_registroreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 257, 101, -1));
        getContentPane().add(txtdireccion_registroreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 137, 122, -1));
        getContentPane().add(txttelefono_registroreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 177, 122, -1));
        getContentPane().add(txtagencia_registroreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 217, 122, -1));

        jLabel10.setText("Fecha Inicio");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 260, 85, -1));
        getContentPane().add(txtfechainicio_registroreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 257, 122, -1));
        getContentPane().add(txtcatidadpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 297, 122, -1));
        getContentPane().add(txtcantidadhabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 337, 122, -1));

        comboboxtipohabitacion_registroreserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboboxtipohabitacion_registroreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 337, -1, -1));
        getContentPane().add(txtserviciosadicionales, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 377, 122, -1));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonguardarreserva;
    private javax.swing.JButton botonlimpiarreserva;
    private javax.swing.JButton botonvolver_resgistroreserva;
    private javax.swing.JComboBox<String> comboboxtipohabitacion_registroreserva;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblidreserva;
    private javax.swing.JLabel lblnombrehuesped;
    private javax.swing.JTextField txtagencia_registroreserva;
    private javax.swing.JTextField txtcantidadhabitaciones;
    private javax.swing.JTextField txtcatidadpersona;
    private javax.swing.JTextField txtdireccion_registroreserva;
    private javax.swing.JTextField txtfechafin_registroreserva;
    private javax.swing.JTextField txtfechainicio_registroreserva;
    private javax.swing.JTextField txtidreserva;
    private javax.swing.JTextField txtnombrehuesped_resgistroreserva;
    private javax.swing.JTextField txtserviciosadicionales;
    private javax.swing.JTextField txttelefono_registroreserva;
    // End of variables declaration//GEN-END:variables
}
