/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author jnosp
 */
public class VistaRegistroAgencia extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroAgencia
     */
    public VistaRegistroAgencia() {
        initComponents();
    }

    public JButton getBotonguardaragencia() {
        return botonguardaragencia;
    }

    public JButton getBotonlimpiaragencia() {
        return botonlimpiaragencia;
    }

    public JButton getBotonvolver_registroagencia() {
        return botonvolver_registroagencia;
    }

    public JTextField getTxtdireccionagencia() {
        return txtdireccionagencia;
    }

    public JTextField getTxtidagencia() {
        return txtidagencia;
    }

    public JTextField getTxtnombreagencia() {
        return txtnombreagencia;
    }

    public JTextField getTxttelefonoagencia() {
        return txttelefonoagencia;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblidagencia = new javax.swing.JLabel();
        lblnombreagencia = new javax.swing.JLabel();
        lbltelefonoagencia = new javax.swing.JLabel();
        lbldireccionagencia = new javax.swing.JLabel();
        botonguardaragencia = new javax.swing.JButton();
        botonlimpiaragencia = new javax.swing.JButton();
        botonvolver_registroagencia = new javax.swing.JButton();
        txtidagencia = new javax.swing.JTextField();
        txtnombreagencia = new javax.swing.JTextField();
        txttelefonoagencia = new javax.swing.JTextField();
        txtdireccionagencia = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblidagencia.setText("ID Agencia");
        getContentPane().add(lblidagencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 33, 83, -1));

        lblnombreagencia.setText("Nombre");
        getContentPane().add(lblnombreagencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 85, 83, -1));

        lbltelefonoagencia.setText("Teléfono");
        getContentPane().add(lbltelefonoagencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 133, 83, -1));

        lbldireccionagencia.setText("Dirección");
        getContentPane().add(lbldireccionagencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 176, 83, -1));

        botonguardaragencia.setBackground(new java.awt.Color(0, 0, 0));
        botonguardaragencia.setForeground(new java.awt.Color(255, 255, 255));
        botonguardaragencia.setText("Guardar");
        getContentPane().add(botonguardaragencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 238, -1, -1));

        botonlimpiaragencia.setBackground(new java.awt.Color(0, 0, 0));
        botonlimpiaragencia.setForeground(new java.awt.Color(255, 255, 255));
        botonlimpiaragencia.setText("Limpiar");
        getContentPane().add(botonlimpiaragencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 238, -1, -1));

        botonvolver_registroagencia.setBackground(new java.awt.Color(0, 0, 0));
        botonvolver_registroagencia.setForeground(new java.awt.Color(255, 255, 255));
        botonvolver_registroagencia.setText("Volver");
        getContentPane().add(botonvolver_registroagencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 238, -1, -1));
        getContentPane().add(txtidagencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 30, 129, -1));
        getContentPane().add(txtnombreagencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 82, 129, -1));
        getContentPane().add(txttelefonoagencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 130, 129, -1));
        getContentPane().add(txtdireccionagencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 176, 129, -1));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroAgencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonguardaragencia;
    private javax.swing.JButton botonlimpiaragencia;
    private javax.swing.JButton botonvolver_registroagencia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbldireccionagencia;
    private javax.swing.JLabel lblidagencia;
    private javax.swing.JLabel lblnombreagencia;
    private javax.swing.JLabel lbltelefonoagencia;
    private javax.swing.JTextField txtdireccionagencia;
    private javax.swing.JTextField txtidagencia;
    private javax.swing.JTextField txtnombreagencia;
    private javax.swing.JTextField txttelefonoagencia;
    // End of variables declaration//GEN-END:variables
}
