package Vista;

import javax.swing.JButton;
import javax.swing.JTable;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jnosp
 */
public class VistaConsultaHoteles extends javax.swing.JFrame {

    /**
     * Creates new form VistaConsultaHoteles
     */
    public VistaConsultaHoteles() {
        initComponents();
    }

    public JButton getBontonvolver_consultahotel() {
        return bontonvolver_consultahotel;
    }

    public JButton getBotonconsultarhotel_consultahotel() {
        return botonconsultarhotel_consultahotel;
    }

    public JButton getBotoneliminarhotel_consultahotel() {
        return botoneliminarhotel_consultahotel;
    }

    public JButton getBotonmodificarhotel_consultahotel() {
        return botonmodificarhotel_consultahotel;
    }

    public JTable getTablaconsultarhoteles() {
        return tablaconsultarhoteles;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsultarhoteles = new javax.swing.JTable();
        botonconsultarhotel_consultahotel = new javax.swing.JButton();
        botoneliminarhotel_consultahotel = new javax.swing.JButton();
        botonmodificarhotel_consultahotel = new javax.swing.JButton();
        bontonvolver_consultahotel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaconsultarhoteles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaconsultarhoteles);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 51, 461, 315));

        botonconsultarhotel_consultahotel.setBackground(new java.awt.Color(0, 0, 0));
        botonconsultarhotel_consultahotel.setForeground(new java.awt.Color(255, 255, 255));
        botonconsultarhotel_consultahotel.setText("Consultar");
        getContentPane().add(botonconsultarhotel_consultahotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 265, -1, -1));

        botoneliminarhotel_consultahotel.setBackground(new java.awt.Color(0, 0, 0));
        botoneliminarhotel_consultahotel.setForeground(new java.awt.Color(255, 255, 255));
        botoneliminarhotel_consultahotel.setText("Eliminar");
        getContentPane().add(botoneliminarhotel_consultahotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 265, -1, -1));

        botonmodificarhotel_consultahotel.setBackground(new java.awt.Color(0, 0, 0));
        botonmodificarhotel_consultahotel.setForeground(new java.awt.Color(255, 255, 255));
        botonmodificarhotel_consultahotel.setText("Modificar");
        getContentPane().add(botonmodificarhotel_consultahotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 316, -1, -1));

        bontonvolver_consultahotel.setBackground(new java.awt.Color(0, 0, 0));
        bontonvolver_consultahotel.setForeground(new java.awt.Color(255, 255, 255));
        bontonvolver_consultahotel.setText("Volver");
        getContentPane().add(bontonvolver_consultahotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 316, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/hoteles.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(580, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConsultaHoteles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bontonvolver_consultahotel;
    private javax.swing.JButton botonconsultarhotel_consultahotel;
    private javax.swing.JButton botoneliminarhotel_consultahotel;
    private javax.swing.JButton botonmodificarhotel_consultahotel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaconsultarhoteles;
    // End of variables declaration//GEN-END:variables
}
