/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author jnosp
 */
public class VistaRegistroHotel extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroHotel
     */
    public VistaRegistroHotel() {
        initComponents();
    }

    public JButton getBotonguardarhotel() {
        return botonguardarhotel;
    }

    public JButton getBotonlimpiarhotel() {
        return botonlimpiarhotel;
    }

    public JButton getBotonvolver_registrohotel() {
        return botonvolver_registrohotel;
    }

    public JComboBox<String> getComboboxcategoria() {
        return comboboxcategoria;
    }

    public JTextField getTxtanioinauguracion() {
        return txtanioinauguracion;
    }

    public JTextField getTxtdireccionhotel() {
        return txtdireccionhotel;
    }

    public JTextField getTxtnombrehotel() {
        return txtnombrehotel;
    }

    public JTextField getTxttelefonohotel() {
        return txttelefonohotel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnombrehotel = new javax.swing.JLabel();
        txtnombrehotel = new javax.swing.JTextField();
        lbldireccionhotel = new javax.swing.JLabel();
        lbltelefonohotel = new javax.swing.JLabel();
        lblanioinauguracion = new javax.swing.JLabel();
        lblcategoria = new javax.swing.JLabel();
        botonguardarhotel = new javax.swing.JButton();
        botonlimpiarhotel = new javax.swing.JButton();
        botonvolver_registrohotel = new javax.swing.JButton();
        txtdireccionhotel = new javax.swing.JTextField();
        txttelefonohotel = new javax.swing.JTextField();
        txtanioinauguracion = new javax.swing.JTextField();
        comboboxcategoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnombrehotel.setText("Nombre del hotel");

        lbldireccionhotel.setText("Dirección");

        lbltelefonohotel.setText("Teléfono");

        lblanioinauguracion.setText("Año de inauguración");

        lblcategoria.setText("Categoría");

        botonguardarhotel.setText("Guardar");

        botonlimpiarhotel.setText("Limpiar");

        botonvolver_registrohotel.setText("Volver");

        comboboxcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Estrella", "2 Estrellas", "3 Estrellas", "4 Estrellas", "5 Estrellas" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbltelefonohotel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbldireccionhotel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblanioinauguracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblnombrehotel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombrehotel, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(txtdireccionhotel)
                            .addComponent(txttelefonohotel)
                            .addComponent(txtanioinauguracion)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(comboboxcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonguardarhotel)
                        .addGap(39, 39, 39)
                        .addComponent(botonlimpiarhotel)
                        .addGap(42, 42, 42)
                        .addComponent(botonvolver_registrohotel)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombrehotel)
                    .addComponent(txtnombrehotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldireccionhotel)
                    .addComponent(txtdireccionhotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelefonohotel)
                    .addComponent(txttelefonohotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblanioinauguracion)
                    .addComponent(txtanioinauguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcategoria)
                    .addComponent(comboboxcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonguardarhotel)
                    .addComponent(botonlimpiarhotel)
                    .addComponent(botonvolver_registrohotel))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonguardarhotel;
    private javax.swing.JButton botonlimpiarhotel;
    private javax.swing.JButton botonvolver_registrohotel;
    private javax.swing.JComboBox<String> comboboxcategoria;
    private javax.swing.JLabel lblanioinauguracion;
    private javax.swing.JLabel lblcategoria;
    private javax.swing.JLabel lbldireccionhotel;
    private javax.swing.JLabel lblnombrehotel;
    private javax.swing.JLabel lbltelefonohotel;
    private javax.swing.JTextField txtanioinauguracion;
    private javax.swing.JTextField txtdireccionhotel;
    private javax.swing.JTextField txtnombrehotel;
    private javax.swing.JTextField txttelefonohotel;
    // End of variables declaration//GEN-END:variables
}
