/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author jnosp
 */
public class VistaConsultaReservas extends javax.swing.JFrame {

    /**
     * Creates new form VistaConsultaReservas
     */
    public VistaConsultaReservas() {
        initComponents();
    }

    public JButton getBotonconsultareserva_consultareseva() {
        return botonconsultareserva_consultareseva;
    }

    public JButton getBotoneliminarreserva_consultareseva() {
        return botoneliminarreserva_consultareseva;
    }

    public JButton getBotonmodificarreserva_consultareseva() {
        return botonmodificarreserva_consultareseva;
    }

    public JButton getBotonvolver_consultareseva() {
        return botonvolver_consultareseva;
    }

    public JTable getTablaconsultareserva() {
        return tablaconsultareserva;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsultareserva = new javax.swing.JTable();
        botonconsultareserva_consultareseva = new javax.swing.JButton();
        botonmodificarreserva_consultareseva = new javax.swing.JButton();
        botoneliminarreserva_consultareseva = new javax.swing.JButton();
        botonvolver_consultareseva = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaconsultareserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaconsultareserva);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 17, -1, 275));

        botonconsultareserva_consultareseva.setBackground(new java.awt.Color(0, 0, 0));
        botonconsultareserva_consultareseva.setForeground(new java.awt.Color(255, 255, 255));
        botonconsultareserva_consultareseva.setText("Consultar");
        getContentPane().add(botonconsultareserva_consultareseva, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 198, -1, -1));

        botonmodificarreserva_consultareseva.setBackground(new java.awt.Color(0, 0, 0));
        botonmodificarreserva_consultareseva.setForeground(new java.awt.Color(255, 255, 255));
        botonmodificarreserva_consultareseva.setText("Modificar");
        getContentPane().add(botonmodificarreserva_consultareseva, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 252, -1, -1));

        botoneliminarreserva_consultareseva.setBackground(new java.awt.Color(0, 0, 0));
        botoneliminarreserva_consultareseva.setForeground(new java.awt.Color(255, 255, 255));
        botoneliminarreserva_consultareseva.setText("Eliminar");
        getContentPane().add(botoneliminarreserva_consultareseva, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 198, -1, -1));

        botonvolver_consultareseva.setBackground(new java.awt.Color(0, 0, 0));
        botonvolver_consultareseva.setForeground(new java.awt.Color(255, 255, 255));
        botonvolver_consultareseva.setText("Volver");
        getContentPane().add(botonvolver_consultareseva, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 252, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/reservas.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addContainerGap(557, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConsultaReservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonconsultareserva_consultareseva;
    private javax.swing.JButton botoneliminarreserva_consultareseva;
    private javax.swing.JButton botonmodificarreserva_consultareseva;
    private javax.swing.JButton botonvolver_consultareseva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaconsultareserva;
    // End of variables declaration//GEN-END:variables
}
