/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author jnosp
 */
public class VistaRegistroAgencia extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroAgencia
     */
    public VistaRegistroAgencia() {
        initComponents();
    }

    public JButton getBotonguardaragencia() {
        return botonguardaragencia;
    }

    public JButton getBotonlimpiaragencia() {
        return botonlimpiaragencia;
    }

    public JButton getBotonvolver_registroagencia() {
        return botonvolver_registroagencia;
    }

    public JTextField getTxtdireccionagencia() {
        return txtdireccionagencia;
    }

    public JTextField getTxtidagencia() {
        return txtidagencia;
    }

    public JTextField getTxtnombreagencia() {
        return txtnombreagencia;
    }

    public JTextField getTxttelefonoagencia() {
        return txttelefonoagencia;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblidagencia = new javax.swing.JLabel();
        lblnombreagencia = new javax.swing.JLabel();
        lbltelefonoagencia = new javax.swing.JLabel();
        lbldireccionagencia = new javax.swing.JLabel();
        botonguardaragencia = new javax.swing.JButton();
        botonlimpiaragencia = new javax.swing.JButton();
        botonvolver_registroagencia = new javax.swing.JButton();
        txtidagencia = new javax.swing.JTextField();
        txtnombreagencia = new javax.swing.JTextField();
        txttelefonoagencia = new javax.swing.JTextField();
        txtdireccionagencia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblidagencia.setText("ID Agencia");

        lblnombreagencia.setText("Nombre");

        lbltelefonoagencia.setText("Teléfono");

        lbldireccionagencia.setText("Dirección");

        botonguardaragencia.setText("Guardar");

        botonlimpiaragencia.setText("Limpiar");

        botonvolver_registroagencia.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblidagencia, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(lblnombreagencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltelefonoagencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbldireccionagencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtidagencia, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addComponent(txtnombreagencia)
                                .addComponent(txtdireccionagencia))
                            .addComponent(txttelefonoagencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(botonguardaragencia)
                        .addGap(48, 48, 48)
                        .addComponent(botonlimpiaragencia)
                        .addGap(30, 30, 30)
                        .addComponent(botonvolver_registroagencia)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidagencia)
                    .addComponent(txtidagencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombreagencia)
                    .addComponent(txtnombreagencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelefonoagencia)
                    .addComponent(txttelefonoagencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldireccionagencia)
                    .addComponent(txtdireccionagencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonguardaragencia)
                    .addComponent(botonlimpiaragencia)
                    .addComponent(botonvolver_registroagencia))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroAgencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonguardaragencia;
    private javax.swing.JButton botonlimpiaragencia;
    private javax.swing.JButton botonvolver_registroagencia;
    private javax.swing.JLabel lbldireccionagencia;
    private javax.swing.JLabel lblidagencia;
    private javax.swing.JLabel lblnombreagencia;
    private javax.swing.JLabel lbltelefonoagencia;
    private javax.swing.JTextField txtdireccionagencia;
    private javax.swing.JTextField txtidagencia;
    private javax.swing.JTextField txtnombreagencia;
    private javax.swing.JTextField txttelefonoagencia;
    // End of variables declaration//GEN-END:variables
}
