
package Vista;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.Image;
import javax.swing.JButton;

/**
 *
 * @author jnosp
 */
public class VistaConsulta extends javax.swing.JFrame {

    
    public JButton getBotonconsultaagencias() {
        return botonconsultaagencias;
    }

    public JButton getBotonconsultahabitaciones() {
        return botonconsultahabitaciones;
    }

    public JButton getBotonconsultahoteles() {
        return botonconsultahoteles;
    }

    public JButton getBotonconsultahuespedes() {
        return botonconsultahuespedes;
    }

    public JButton getBotonconsultareservas() {
        return botonconsultareservas;
    }

    /**
     * Creates new form VistaConsulta
     */
    public JButton getBotonregresomenu() {    
        return botonregresomenu_consulta;
    }

    public VistaConsulta() {
        initComponents();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonconsultahoteles = new javax.swing.JButton();
        botonconsultareservas = new javax.swing.JButton();
        botonconsultaagencias = new javax.swing.JButton();
        botonconsultahabitaciones = new javax.swing.JButton();
        botonregresomenu_consulta = new javax.swing.JButton();
        botonconsultahuespedes = new javax.swing.JButton();
        JlavelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonconsultahoteles.setText("Consultar Hoteles");
        getContentPane().add(botonconsultahoteles, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        botonconsultareservas.setText("Consultar Reservas");
        getContentPane().add(botonconsultareservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        botonconsultaagencias.setText("Consultar Agencias");
        getContentPane().add(botonconsultaagencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        botonconsultahabitaciones.setText("Consultar Habitaciones");
        getContentPane().add(botonconsultahabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        botonregresomenu_consulta.setText("Volver al Menú Principal");
        getContentPane().add(botonregresomenu_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        botonconsultahuespedes.setText("Consultar Huéspedes");
        getContentPane().add(botonconsultahuespedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        JlavelFondo.setBackground(new java.awt.Color(204, 0, 0));
        JlavelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/hotel.png"))); // NOI18N
        JlavelFondo.setOpaque(true);
        getContentPane().add(JlavelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlavelFondo;
    private javax.swing.JButton botonconsultaagencias;
    private javax.swing.JButton botonconsultahabitaciones;
    private javax.swing.JButton botonconsultahoteles;
    private javax.swing.JButton botonconsultahuespedes;
    private javax.swing.JButton botonconsultareservas;
    private javax.swing.JButton botonregresomenu_consulta;
    // End of variables declaration//GEN-END:variables
}
