/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author jnosp
 */
public class VistaConsultaHabitaciones extends javax.swing.JFrame {

    /**
     * Creates new form VistaConsultaHabitaciones
     */
    public VistaConsultaHabitaciones() {
        initComponents();
    }

    public JButton getBontonvolver_consultahabitacion() {
        return bontonvolver_consultahabitacion;
    }

    public JButton getBotonaliminarhabitacion_consultahabitacion() {
        return botonaliminarhabitacion_consultahabitacion;
    }

    public JButton getBotonconsultarhabitacion_consultahabitacion() {
        return botonconsultarhabitacion_consultahabitacion;
    }

    public JButton getBotonmodificarhabitacion_consultahabitacion() {
        return botonmodificarhabitacion_consultahabitacion;
    }

    public JTable getTablaconsultahabitacion() {
        return tablaconsultahabitacion;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsultahabitacion = new javax.swing.JTable();
        botonconsultarhabitacion_consultahabitacion = new javax.swing.JButton();
        botonaliminarhabitacion_consultahabitacion = new javax.swing.JButton();
        botonmodificarhabitacion_consultahabitacion = new javax.swing.JButton();
        bontonvolver_consultahabitacion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaconsultahabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaconsultahabitacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 40, 375, 275));

        botonconsultarhabitacion_consultahabitacion.setBackground(new java.awt.Color(0, 0, 0));
        botonconsultarhabitacion_consultahabitacion.setForeground(new java.awt.Color(255, 255, 255));
        botonconsultarhabitacion_consultahabitacion.setText("Consultar");
        getContentPane().add(botonconsultarhabitacion_consultahabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 232, -1, -1));

        botonaliminarhabitacion_consultahabitacion.setBackground(new java.awt.Color(0, 0, 0));
        botonaliminarhabitacion_consultahabitacion.setForeground(new java.awt.Color(255, 255, 255));
        botonaliminarhabitacion_consultahabitacion.setText("Eliminar");
        getContentPane().add(botonaliminarhabitacion_consultahabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 232, -1, -1));

        botonmodificarhabitacion_consultahabitacion.setBackground(new java.awt.Color(0, 0, 0));
        botonmodificarhabitacion_consultahabitacion.setForeground(new java.awt.Color(255, 255, 255));
        botonmodificarhabitacion_consultahabitacion.setText("Modificar");
        getContentPane().add(botonmodificarhabitacion_consultahabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 284, -1, -1));

        bontonvolver_consultahabitacion.setBackground(new java.awt.Color(0, 0, 0));
        bontonvolver_consultahabitacion.setForeground(new java.awt.Color(255, 255, 255));
        bontonvolver_consultahabitacion.setText("Volver");
        getContentPane().add(bontonvolver_consultahabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 284, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/habitacion.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addContainerGap(480, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 710, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConsultaHabitaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bontonvolver_consultahabitacion;
    private javax.swing.JButton botonaliminarhabitacion_consultahabitacion;
    private javax.swing.JButton botonconsultarhabitacion_consultahabitacion;
    private javax.swing.JButton botonmodificarhabitacion_consultahabitacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaconsultahabitacion;
    // End of variables declaration//GEN-END:variables
}
