/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author jnosp
 */
public class VistaRegistroHuesped extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroHuesped
     */
    public VistaRegistroHuesped() {
        initComponents();
    }

    public JButton getBotonguardarhuesped() {
        return botonguardarhuesped;
    }

    public JButton getBotonlimpiarhuesped() {
        return botonlimpiarhuesped;
    }

    public JButton getBotonvolver_resgistrohuesped() {
        return botonvolver_resgistrohuesped;
    }

    public JTextField getTxtdireccionhuesped_registrohuesped() {
        return txtdireccionhuesped_registrohuesped;
    }

    public JTextField getTxtfechantohuesped_registrohuesped() {
        return txtfechantohuesped_registrohuesped;
    }

    public JTextField getTxtidhuesped_registrohuesped() {
        return txtidhuesped_registrohuesped;
    }

    public JTextField getTxtnombrehuesped_resgistrohuesped() {
        return txtnombrehuesped_resgistrohuesped;
    }

    public JTextField getTxttelefonohuesped_registrohuesped() {
        return txttelefonohuesped_registrohuesped;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblhuesped = new javax.swing.JLabel();
        lblnombrehuesped = new javax.swing.JLabel();
        lbldireccionhuesped = new javax.swing.JLabel();
        lbltelefonohuesped = new javax.swing.JLabel();
        lblfechanto = new javax.swing.JLabel();
        botonguardarhuesped = new javax.swing.JButton();
        botonlimpiarhuesped = new javax.swing.JButton();
        botonvolver_resgistrohuesped = new javax.swing.JButton();
        txtidhuesped_registrohuesped = new javax.swing.JTextField();
        txtdireccionhuesped_registrohuesped = new javax.swing.JTextField();
        txtnombrehuesped_resgistrohuesped = new javax.swing.JTextField();
        txttelefonohuesped_registrohuesped = new javax.swing.JTextField();
        txtfechantohuesped_registrohuesped = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblhuesped.setText("ID Huésped");

        lblnombrehuesped.setText("Nombre completo");

        lbldireccionhuesped.setText("Dirección");

        lbltelefonohuesped.setText("Teléfono");

        lblfechanto.setText("Fecha de nacimiento");

        botonguardarhuesped.setText("Guardar");

        botonlimpiarhuesped.setText("Limpiar");

        botonvolver_resgistrohuesped.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblhuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(botonguardarhuesped)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(botonlimpiarhuesped)
                                .addGap(34, 34, 34)
                                .addComponent(botonvolver_resgistrohuesped))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdireccionhuesped_registrohuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtidhuesped_registrohuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombrehuesped_resgistrohuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttelefonohuesped_registrohuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfechantohuesped_registrohuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnombrehuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltelefonohuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldireccionhuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblfechanto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhuesped)
                    .addComponent(txtidhuesped_registrohuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombrehuesped)
                    .addComponent(txtnombrehuesped_resgistrohuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldireccionhuesped)
                    .addComponent(txtdireccionhuesped_registrohuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelefonohuesped)
                    .addComponent(txttelefonohuesped_registrohuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblfechanto)
                    .addComponent(txtfechantohuesped_registrohuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonguardarhuesped)
                    .addComponent(botonlimpiarhuesped)
                    .addComponent(botonvolver_resgistrohuesped))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroHuesped().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonguardarhuesped;
    private javax.swing.JButton botonlimpiarhuesped;
    private javax.swing.JButton botonvolver_resgistrohuesped;
    private javax.swing.JLabel lbldireccionhuesped;
    private javax.swing.JLabel lblfechanto;
    private javax.swing.JLabel lblhuesped;
    private javax.swing.JLabel lblnombrehuesped;
    private javax.swing.JLabel lbltelefonohuesped;
    private javax.swing.JTextField txtdireccionhuesped_registrohuesped;
    private javax.swing.JTextField txtfechantohuesped_registrohuesped;
    private javax.swing.JTextField txtidhuesped_registrohuesped;
    private javax.swing.JTextField txtnombrehuesped_resgistrohuesped;
    private javax.swing.JTextField txttelefonohuesped_registrohuesped;
    // End of variables declaration//GEN-END:variables
}
