/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author jnosp
 */
public class VistaConsultaAgencias extends javax.swing.JFrame {

    
    public JButton getBontonvolver_consultaagencias() {
        return bontonvolver_consultaagencias;
    }

    public JButton getBotonconsultaagencia_consultaagencia() {
        return botonconsultaagencia_consultaagencia;
    }

    public JButton getBotoneliminaragencias_consultaagencias() {
        return botoneliminaragencias_consultaagencias;
    }

    public JButton getBotonmodificaragencias_consultaagencias() {
        return botonmodificaragencias_consultaagencias;
    }

    /**
     * Creates new form VistaConsultaAgencias
     */
    public JTable getTablaconsultaagencias() {    
        return tablaconsultaagencias;
    }

    public VistaConsultaAgencias() {
        initComponents();
       
}


 
    
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsultaagencias = new javax.swing.JTable();
        botonconsultaagencia_consultaagencia = new javax.swing.JButton();
        botoneliminaragencias_consultaagencias = new javax.swing.JButton();
        botonmodificaragencias_consultaagencias = new javax.swing.JButton();
        bontonvolver_consultaagencias = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaconsultaagencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaconsultaagencias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 6, 375, 275));

        botonconsultaagencia_consultaagencia.setBackground(new java.awt.Color(0, 0, 0));
        botonconsultaagencia_consultaagencia.setForeground(new java.awt.Color(255, 255, 255));
        botonconsultaagencia_consultaagencia.setText("Consultar");
        getContentPane().add(botonconsultaagencia_consultaagencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 186, -1, -1));

        botoneliminaragencias_consultaagencias.setBackground(new java.awt.Color(0, 0, 0));
        botoneliminaragencias_consultaagencias.setForeground(new java.awt.Color(255, 255, 255));
        botoneliminaragencias_consultaagencias.setText("Eliminar");
        getContentPane().add(botoneliminaragencias_consultaagencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 186, -1, -1));

        botonmodificaragencias_consultaagencias.setBackground(new java.awt.Color(0, 0, 0));
        botonmodificaragencias_consultaagencias.setForeground(new java.awt.Color(255, 255, 255));
        botonmodificaragencias_consultaagencias.setText("Modificar");
        getContentPane().add(botonmodificaragencias_consultaagencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 237, -1, -1));

        bontonvolver_consultaagencias.setBackground(new java.awt.Color(0, 0, 0));
        bontonvolver_consultaagencias.setForeground(new java.awt.Color(255, 255, 255));
        bontonvolver_consultaagencias.setText("Volver");
        getContentPane().add(bontonvolver_consultaagencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 237, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/agencias.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 170, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 720, 310));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaAgencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaAgencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaAgencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaAgencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConsultaAgencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bontonvolver_consultaagencias;
    private javax.swing.JButton botonconsultaagencia_consultaagencia;
    private javax.swing.JButton botoneliminaragencias_consultaagencias;
    private javax.swing.JButton botonmodificaragencias_consultaagencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaconsultaagencias;
    // End of variables declaration//GEN-END:variables
}
