package Vista;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jnosp
 */
public class VistaConsultaHoteles extends javax.swing.JFrame {

    /**
     * Creates new form VistaConsultaHoteles
     */
    public VistaConsultaHoteles() {
        initComponents();
    }

    public JButton getBontonvolver_consultahotel() {
        return bontonvolver_consultahotel;
    }

    public JButton getBotonconsultarhotel_consultahotel() {
        return botonconsultarhotel_consultahotel;
    }

    public JButton getBotoneliminarhotel_consultahotel() {
        return botoneliminarhotel_consultahotel;
    }

    public JButton getBotonmodificarhotel_consultahotel() {
        return botonmodificarhotel_consultahotel;
    }

    public JTable getTablaconsultarhoteles() {
        return tablaconsultarhoteles;
    }

    public JTextField getTxtconsulta_añodeinauguracion() {
        return txtconsulta_añodeinauguracion;
    }

    public JTextField getTxtconsulta_direccionhotel() {
        return txtconsulta_direccionhotel;
    }

    public JTextField getTxtconsulta_nombrehotel() {
        return txtconsulta_nombrehotel;
    }

    public JTextField getTxtconsulta_telefonohotel() {
        return txtconsulta_telefonohotel;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsultarhoteles = new javax.swing.JTable();
        botonconsultarhotel_consultahotel = new javax.swing.JButton();
        botoneliminarhotel_consultahotel = new javax.swing.JButton();
        botonmodificarhotel_consultahotel = new javax.swing.JButton();
        bontonvolver_consultahotel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtconsulta_nombrehotel = new javax.swing.JTextField();
        txtconsulta_direccionhotel = new javax.swing.JTextField();
        txtconsulta_telefonohotel = new javax.swing.JTextField();
        txtconsulta_añodeinauguracion = new javax.swing.JTextField();
        comoboxconsulta_categoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaconsultarhoteles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaconsultarhoteles);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 51, 461, 315));

        botonconsultarhotel_consultahotel.setText("Consultar");
        getContentPane().add(botonconsultarhotel_consultahotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 265, -1, -1));

        botoneliminarhotel_consultahotel.setText("Eliminar");
        getContentPane().add(botoneliminarhotel_consultahotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 265, -1, -1));

        botonmodificarhotel_consultahotel.setText("Modificar");
        getContentPane().add(botonmodificarhotel_consultahotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 316, -1, -1));

        bontonvolver_consultahotel.setText("Volver");
        getContentPane().add(bontonvolver_consultahotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 316, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel2.setText("Nombre del hotel");

        jLabel3.setText("Direccion");

        jLabel4.setText("Telefono");

        jLabel5.setText("Año de inauguracion");

        jLabel6.setText("Categoria");

        comoboxconsulta_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Estrella", "2 Estrellas", "3 Estrellas", "4 Estrellas", "5 Estrellas", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtconsulta_nombrehotel)
                    .addComponent(txtconsulta_direccionhotel)
                    .addComponent(txtconsulta_telefonohotel)
                    .addComponent(txtconsulta_añodeinauguracion)
                    .addComponent(comoboxconsulta_categoria, 0, 104, Short.MAX_VALUE))
                .addContainerGap(510, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtconsulta_nombrehotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtconsulta_direccionhotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtconsulta_telefonohotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtconsulta_añodeinauguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(comoboxconsulta_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConsultaHoteles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bontonvolver_consultahotel;
    private javax.swing.JButton botonconsultarhotel_consultahotel;
    private javax.swing.JButton botoneliminarhotel_consultahotel;
    private javax.swing.JButton botonmodificarhotel_consultahotel;
    private javax.swing.JComboBox<String> comoboxconsulta_categoria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaconsultarhoteles;
    private javax.swing.JTextField txtconsulta_añodeinauguracion;
    private javax.swing.JTextField txtconsulta_direccionhotel;
    private javax.swing.JTextField txtconsulta_nombrehotel;
    private javax.swing.JTextField txtconsulta_telefonohotel;
    // End of variables declaration//GEN-END:variables
}
